services:
  otrs:
    image: juanluisbaptiste/otrs:latest
    build: 
      context: ./otrs
    ports:
      - '80:80'
    depends_on:
      - mariadb
    environment:
      - OTRS_DB_PASSWORD=${OTRS_DB_PASSWORD:-changeme}
      - OTRS_ROOT_PASSWORD=${OTRS_ROOT_PASSWORD:-changeme}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-changeme}
      - OTRS_DB_NAME=${OTRS_DB_NAME:-otrs}
      - OTRS_DB_USER=${OTRS_DB_USER:-otrs}
      - OTRS_DB_HOST=${OTRS_DB_HOST:-mariadb}
      - OTRS_DB_PORT=${OTRS_DB_PORT:-3306}
    volumes:
      - './volumes/config:/opt/otrs/Kernel'
      - './volumes/skins:/opt/otrs/var/httpd/htdocs/skins/'
      - './backups:/var/otrs/backups'
      - './volumes/addons:/opt/otrs/addons'
      - './volumes/db_upgrade:/opt/otrs/db_upgrade'
      - '/etc/localtime:/etc/localtime:ro'
  mariadb:
    image: juanluisbaptiste/otrs-mariadb:latest
    build:
      context: ./mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-changeme}
    expose:
      - "3306"
    volumes:
      - './volumes/mysql:/var/lib/mysql'
      - '/etc/localtime:/etc/localtime:ro'
